version: '3'

x-database-credentials: &database-credentials
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: timeguess
  MYSQL_USER: timeguess
  MYSQL_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/timeguess
  SPRING_JPA_HIBERNATE_DDL_AUTO: update

services:
  webapp:
    image: timeguess-webapp
    restart: always
    ports:
      - 8080:8080
    environment: *database-credentials
    depends_on:
      - database
    volumes:
      - ./:/timeguess
  database:
    image: mysql:8.0
    restart: always
    environment: *database-credentials
    volumes:
    - database:/var/lib/mysql
    ports:
      - 8081:3306
volumes:
  database: