-- users

INSERT INTO USER (PASSWORD, USERNAME, email) VALUES('$2a$10$3Z6v.cUNfLxqpgGanZp.VeBMncNoiP5bW4HDNDvsWeAGf.OFzaKYu', 'admin', 'admin@aimlib.at');
INSERT INTO USER_USER_ROLE (USER_ID, ROLES) SELECT ID, 'ROLE_USER' FROM user WHERE username = 'admin';
INSERT INTO USER_USER_ROLE (USER_ID, ROLES) SELECT ID, 'ROLE_MANAGER' FROM user WHERE username = 'admin';
INSERT INTO USER_USER_ROLE (USER_ID, ROLES) SELECT ID, 'ROLE_ADMIN' FROM user WHERE username = 'admin';
INSERT INTO USER (PASSWORD, USERNAME, EMAIL) VALUES('$2a$10$3Z6v.cUNfLxqpgGanZp.VeBMncNoiP5bW4HDNDvsWeAGf.OFzaKYu', 'user1', 'susi@aimlib.com');
INSERT INTO USER_USER_ROLE (USER_ID, ROLES) SELECT ID, 'ROLE_USER' FROM user WHERE username = 'user1';
INSERT INTO USER_USER_ROLE (USER_ID, ROLES) SELECT ID, 'ROLE_MANAGER' FROM user WHERE username = 'user1';
INSERT INTO USER (PASSWORD, USERNAME, email) VALUES('$2a$10$3Z6v.cUNfLxqpgGanZp.VeBMncNoiP5bW4HDNDvsWeAGf.OFzaKYu', 'user2', 'user@aimlib.at');
INSERT INTO USER_USER_ROLE (USER_ID, ROLES) SELECT ID, 'ROLE_USER' FROM user WHERE username = 'user2';
INSERT INTO USER (PASSWORD, USERNAME, email) VALUES('$2a$10$3Z6v.cUNfLxqpgGanZp.VeBMncNoiP5bW4HDNDvsWeAGf.OFzaKYu', 'user3', 'steve@aimlib.at');
INSERT INTO USER_USER_ROLE (USER_ID, ROLES) SELECT ID, 'ROLE_USER' FROM user WHERE username = 'user3';
INSERT INTO USER (PASSWORD, USERNAME, email) VALUES('$2a$10$3Z6v.cUNfLxqpgGanZp.VeBMncNoiP5bW4HDNDvsWeAGf.OFzaKYu', 'laura', 'laura@aimlib.at');