INSERT INTO user_role (name, created_at, updated_at) VALUES
    ('USER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('MANAGER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('ADMIN', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
